In [1]:
import numpy as np


### Arreglos en Numpy

Un arreglo es una estructura de datos que permite almacenar elementos de un mismo tipo. En Numpy, un arreglo solo puede tener un tipo de dato.

In [9]:
np.array( [1, 2, 3, 4, 5] )

array([1, 2, 3, 4, 5])

Podemos guardar arreglos en variables.

In [10]:
a = np.array([1, 2, 3, 4, 5])

Cada arreglo tiene un id único que lo identifica en memoria.

In [11]:
id(a)

140032505112848

Size nos indica el tamaño del arreglo, es decir, el número de elementos que contiene.

In [12]:
a.size

5

Ndim nos indica el número de dimensiones del arreglo, es decir, si es un arreglo unidimensional, bidimensional, etc.

In [13]:
a.ndim

1

Dtype nos indica el tipo de dato que contiene el arreglo.

In [14]:
a.dtype

dtype('int64')

Shape nos indica el número de elementos en cada dimensión del arreglo.

In [15]:
a.shape

(5,)

### Operaciones con arreglos

Podemos realizar operaciones matemáticas con arreglos. Estas operaciones se aplican elemento por elemento. 
Estas operaciones no modifican el arreglo original, sino que devuelven un nuevo arreglo con el resultado de la operación.

In [16]:
a = np.array([1, 2, 3, 4, 5])
a + 10
a - 10
a * 10
a / 10

array([0.1, 0.2, 0.3, 0.4, 0.5])

También podemos realizar operaciones entre dos arreglos. Para que estas operaciones sean válidas, los arreglos deben tener
el mismo tamaño, es decir, el mismo número de elementos.

In [17]:
a = np.array([1, 2, 3, 4, 5])
b = np.array([3, 5, 9, 5, 1])
a + b

array([ 4,  7, 12,  9,  6])

Podemos decidir que tipo de datos queremos que tenga nuestro arreglo.Basta con especificarlo en el parámetro dtype al 
momento de crear el arreglo. Pueden ser cualquier tipo de dato que soporte numpy. float, int, complex, bool, etc.

In [18]:
a = np.array([1, 2, 3, 4, 5], dtype=float)

### Funciones para crear arreglos

Podemos especificar el tamaño del arreglo, indicando el número de elementos que queremos. El primer parámetro es el valor 
inicial, el segundo es el valor final y el tercer parámetro es el paso entre cada elemento. En este caso, el primer parametro 
indica que empieza en 0, el segundo infdica que termina en 100 y el tercer parametro indica que se listara de 2 en 2.
Cabe recalcar que el valor final no se incluye en el resultado del arreglo, entonces, los arreglos terminan en la cantidad 
menos 1 o el valor indicado en el tercer elemento. Dicho todo eso, el resultado seria un arreglo que va de 0 a 98 de 2 en 2.

In [19]:
np.arange(0, 100, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

Podemos crear arreglos de ceros. El parametro indica la cantidad de elementos, en este caso ceros, que tendra el arreglo. 
Los ceros por default son de tipo float, pero podemos especificar el tipo de dato con el parametro dtype mostrado anteriormente.

In [20]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

Tambien podemos crear arreglos de unos. Y es igual que con los ceros.

In [21]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Con empty podemos crear arreglos con elementos 'basura', es decir, elementos que no tienen un valor definido.

In [22]:
np.empty(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

Con ramdom.radint podemos crear arreglos con números aleatorios enteros. El primer parámetro indica el valor minimo (incluido),
el segundo parametro indica el valor máximo (no incluido) y el tercer parámetro indica la cantidad de elementos que tendrá el arreglo. En este caso, el arreglo tendrá 10 elementos con valores entre 0 y 99.

In [23]:
np.random.randint(0, 100, 10)

array([25, 82, 63, 21, 12, 21, 33, 78, 93, 19])

### Obtener y modificar elementos de un arreglo.

Podemos saber el valor de un elemento en especifico utilizando su índice. En los siguientes ejemplo, se obtiene el primer elemento al utilizar el índice 0, el tercer elemento al utilizar el índice 2 y el penúltimo elemento al utilizar el índice -2.
Recuerda que los indices emplezan de 0 y que el indice -1 hace referencia al último elemento del arreglo.
Los arreglos se 'leen' de izquierda a derecha con numeros positivos y de derecha a izquierda con numeros negativos.

In [24]:
a = np.random.randint(0, 100, 10)

a[0]
a[2]
a[-2]

43

Podemos modificar el valor de un elemento en especifico utilizando su índice
y asignandole un nuevo valor. En este caso, se modifica el primer elemento del arreglo a 100.

In [25]:
a[0] = 100

### Subarreglos

Podemos obtener un subarreglo, es decir, una parte del arreglo original.
Para ello, utilizamos la notación de slicing [], que es similar a la que se utiliza en las listas de python.
El primer parámetro indica el índice de inicio, el segundo el índice de fin y el tercero el paso.
En este caso, estamos obteniendo un subarreglo que comienza en el índice 2, termina en el índice 10 (sin incluirlo) y toma elementos de 2 en 2.

In [26]:
a = np.array([5, 8, 9, 6, 7, 62, 45, 25, 65, 84, 25, 1, 4,])
a[2:10:2]

array([ 9,  7, 45, 65])

Tambien podemos obtener un subarreglo utilizando una lista de indices.
En este caso, estamos obteniendo un subarreglo con los elementos en los indices 2. 8, y 11.

In [27]:
a[ [2, 8, 11]]

array([ 9, 65,  1])

Otra forma de obtener un subarreglo es utilizando una lista de booleanos.
Los elementos que se obtienen para el subarreglo son aquellos que tienen un True en la lista de booleanos.
False indica que el elemento no se incluye en el subarreglo.
La lista de booleanos debe tener la misma cantidad de elementos que el arreglo original.
En este caso, se obtiene un subarreglo con los elementos en las posiciones 0, 2, 7 y 11. 

Esta manera de obtener subarrelos con booleanos es muy útil para condicionar la obtención de elementos.

In [28]:
a[ [True, False, True, False, False, False, False, True, False, False, False, True, False] ]

array([ 5,  9, 25,  1])

### Vectorizar funciones

Podemos aplicar una funcion a un elemento de un arreglo.
En este caso, obtendremos el cuadrado de 6, que es el numero que se pasa como parametro a la funcion.

In [29]:
a = np.array([5, 8, 9, 6, 7, 62, 45, 25, 65, 84, 25, 1, 4,])

In [30]:
def operacion(valor):
    return (valor ** 2) +2

operacion (6)

38

Se puede aplicar un ciclo for para aplicar la funcion a cada elemento del arreglo.
En este caso, se aobtendra el cuadrado de cada elmento del arreglo "a".

In [31]:
for valor in a:
    print(operacion(valor))

27
66
83
38
51
3846
2027
627
4227
7058
627
3
18


Lo anterior es valido, pero existe una forma más eficiente de aplicar una funcion a cada elemento de un arreglo.
Para ello, utilizamos la función np.vectorize, que toma como parámetro la funcion que queremos aplicar
y devuelve un nuevo arreglo con el resultado que se obtiene al aplicar la función a cada elemento.
En este caso, se obtiene un nuevo arreglo con el cuadrado de cada elemento.

In [32]:
vector =np.vectorize(operacion)
vector(a)

array([  27,   66,   83,   38,   51, 3846, 2027,  627, 4227, 7058,  627,
          3,   18])

### Copias y vistas

Podemos crear una copia de un arreglo utilizando el método copy(), aunque tengan los mismos valores y la misma
cantidad de elementos, son dos arreglos diferentes en memoria, totalmente independientes.
O sea, algo como hacer un cambio al arreglo b no afectará al arreglo a.

In [27]:
a = np.array([5, 8, 9, 6, 7, 62, 45, 25, 65, 84, 25, 1, 4,])

In [28]:
b = a.copy()

Podemos crear una vista de un arreglo utilizando el método view().
En este caso, son dos arreglos diferentes en memoria, pero comparten los mismos datos,
es decir, si se hace un cambio en uno, el otro también se verá afectado.

In [29]:
c = a.view()

Aunque cada arreglo tiene un id diferente en memoria, el arreglo c tiene el id base del arreglo a,
lo que indica su relacion.

In [30]:
id(c.base)

133745820681584

### Matrices

Podemos crear matrices, que son arreglos bidimensionales, que contienen una lista de listas. 
Estas matrices están compuestas por filas y columnas, cada fila es una lista y cada columna es un elemento de la lista.
En este caso, tenemos una matriz de 3 filas y 4 columnas.

In [31]:
A = np.array( [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

Al igual que con los arreglos, podemos obtener el tamaño, número de dimensiones, tipo de dato y forma de la matriz.
En este caso, A.ndim nos indica que es una matriz, ya que el resultado de ejecutar A.ndim sera 2.
A.shape nos indica que la matriz tiene 3 filas y 4 columnas, mostrando en resultado (3, 4).

In [32]:
A.ndim
A.shape

(3, 4)

Podemos obtener un elemento en especifico de la matriz utilizando dos indices,
el primer indice indica la fila y el segundo indice indica la columna.
En el primer ejemplo se obtiene el elemento en la fila 0 y la columna 3, es decir, el numero 4. 
En el segundo ejemplo se obtiene el elemento en la fila 2 y la columna 2, es decir, el numero 11.
Recordemos que la lista de filas y columnas comienza en 0, es decir, si queremos obtener datos de la primer fila, debemos indicar 0.
Entonces, si nuestra matriz tiene 3 filas, para obtener datos de la tercer fila tendremos que indicar 2.

In [39]:
A[0][3]
A[2][2]

11

Esta es una segunda opcion de como obtener elementos en especifico de la matriz.
Basicamente es lo mismo, pero los parametros se encuentran en los mismos [] y separados por una coma.
ESta segunada manera es la mas utilizada.

In [40]:
A[0, 3]
A[2][2]

11

Podemos obtener subarreglos apartir de las filas y columnas.
En este caso, el primer parametro indica la fila de donde se extraeran los datos, el segundo parametro (acompañado de ":" antes del numero)
nos indica la cantidad de elementos que se obtendran de la fila indicada.

In [41]:
A[1, :3]
A[2, :2]

array([ 9, 10])

Si queremos obtener los utimos datos de la fila, solo debemos colocar los ":" despues de indicar el segundo parametro.

In [42]:
A[2, 2:]

array([11, 12])

Podemos obtener valores atravez de indices. Basta con definir una lista de los indices.
Al igual que en el ejemplo, el primer parametro indica la fila de donde se extraeran los datos,
despues, dentro de [] se colocaran los indices de los datos que se quieren extraer.
Es decir, en el ejemplo obtendremos los valores en el indice 0 y 4, de la fila 0.

In [44]:
A[0,[0,3]]

array([1, 4])

Tambien podemos obtener elementos de todas las filas y en la misma columna. 
En el ejemplo obtendremos los elementos de todas lss filas que estan en la columna 3.
EL no indicar nada en el primer parametro le dice al programa que se obtendran elementos de todas ls filas,
el segundo parametro indica de que columna se obtendran los elementos.

In [45]:
A[:,3]

array([ 4,  8, 12])

Tambien podemos obtener valores de filas muy puntuales.
En el ejemplo, el primer parametro esta indicado con [0, 2], que indica de que filas obtendremos los elementos,
el segundo parametro, que es 3, indica la columna de la que se obtendran los elementos.

In [46]:
A[[0, 2], 3]

array([ 4, 12])

### Métodos de agregación

In [25]:
A = np.array( [
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 10, 11, 12]
])

Con std() podremos conocer la desviación estandar del arreglo.
Con sum() obtendremos la suma total de todos los elementos.
Con min() conoceremeos el valor minimo existente en el arreglo.
Con max() conoceremos el valor maximo existente en el arreglo.
Con mean() conoceremos el promedio.

In [26]:
A.std()
A.sum()
A.min()
A.max()
A.mean()

6.5

Tambien podemos sumar solo los valores de una fila en concreto.
Basta con agregar el numero de la fula entre [], en este caso obtendremos la suma de la fila 1.
De igual manera se puede aplicar los metodos min, max, etc, para cualquier fila.

In [49]:
A[1].sum()

26

En el caso de las columnas, podemos hacerlo como se muestra en el siguiente ejemplo. 
Dentro de [] en el primer parametro solo dejamos : para indicar que se tomaran los elementos de todas las filas,
en el segundo parametro se indica el numero de la columna donde tomaremos los elementos.
En este caso, obtendremoas el promedio y suma de todos los elementos de la columna 2.

In [50]:
A[:, 2].mean()
A[:, 2].sum()

21

### Transposición

Una transposición es hacer que las filas se conviertan en columnas y las columnas en filas.
Basta con agregar .T para realizarlo.

In [51]:
A.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

Podemos sumar los elementos de las filas haciendo primero la trasposición.
Solo añadimos el numero de la fila a sumar entre [] y el parametro .sum(). 
EL resultado obtenido seria el mismo que obtendriamos de A[:, 2].sum(), que es parte de lo aprendido
unas lineas arriba.

In [52]:
A.T[2].sum()

21

### Filtros y condiciones.

In [53]:
a = np.array([5, 8, 9, 6, 7, 62, 45, 25, 65, 84, 25, 1, 4,])

Podemos condicionar la obtención de valores en nuestro arreglo utilizando operadores logicos. 
En este caso, estamos pidiendo los valores que sean mayores a 50.Pero no es que nos dara los numeros mayores a 50 como 
resultado, lo que obtendremos es un arreglo de boleanos True y False con la misma longitut que el arreglo original, 
los valores True estaran ubicados en la misma posición que los valores mayores a 50, mientras que False estara en las 
ubicaciones de los valores menores a 50. La salida mostrara algo como "array([False, False, True, True]), 
dependiendo del varon y posicion de los elementos.

In [54]:
a > 50

array([False, False, False, False, False,  True, False, False,  True,
        True, False, False, False])

Para obtener un arreglo solo con los valores que cumplen con la condición y no un arreglo de booleanos,
Basta con agregar la condicion entre [].

In [55]:
a[a > 50]

array([62, 65, 84])

Para poder agregar mas condiciones a nuestro arreglo, basta con agregar cada condicion dentro de ()
y el simbolo & entre las condiciones.
En este caso obtendremos solo los valores mayores a 20 y menores que 50.

In [56]:
a[(a > 20) & (a < 50)]

array([45, 25, 25])

Para trabajar con el operador Or basta con implementar el simbolo |.
En este caso, obtedremos los valores que sean iguales a 20 o igyales a 50.

In [57]:
a[(a == 20) | (a == 50)]

array([], dtype=int64)

### Condiciones

Para saber si todos los elementos de un arreglo cumplen o no con una condición,
basta con utilizar el método .all(). Dentro de () debemos colocar la condición a cumplir.
En el ejemplo 1 revisamos si todos los elementos son mayores a 50
y en el ejemplo 2 revisamos si todos los elementos son mayores o iguales a 0.
Los resultados se muestran con valores booleanos, True y False.
Es decir, si todos los elementos cumplen con la condición, el resultado será True,
si no todos los elementos, aun que sea 1, no cumplen con la condición, el resultado será False.

In [58]:
np.all(a > 50)
np.all(a >= 0)

True

Podemos hacer uso de varias condiciones, solo que adiferencia de lo mostrado en la parte de Filtros y condiciones,
las condiciones no se colocan dentro de [], se colocan dentro de () y cada condicion dentro de ().

In [59]:
np.all((a == 20) | (a == 50))

False

Con .any() podemos saber si por lo menos algun elemento de nuestro arreglo cumple con la y/o las condiciones.

In [60]:
np.any(a > 20)

True

### Funciones Where y Select

Where y Select nos permiten crear nuevos arreglos a partir de condiciones y opciones.

In [12]:
calificaciones = np.array( [8, 5, 9, 6, 9, 8, 5, 8, 2, 7])

Mediante la funcion where() vamos a crear un nuevo arreglo apartir de una condicion
y dos tipos de valores (condiciones/mensajes), el primero para cuando la condicion se cumpla y el segundo para cuando no se cumpla.
Lo que se obtiene es un arreglo de mensajes con la misma longitud del arreglo original.
El primer mensaje estara en las posiciones en las que los valores cumplen la condicion,
mientras que el segundo mensaje estara en las posiciones en las que los valores no cumplan la condicion.

In [13]:
np.where(
    calificaciones >= 7,
    'Felicidades, aprobaste la materia.',
    'Lo sentimos, no aprobaste la materia.'
)

array(['Felicidades, aprobaste la materia.',
       'Lo sentimos, no aprobaste la materia.',
       'Felicidades, aprobaste la materia.',
       'Lo sentimos, no aprobaste la materia.',
       'Felicidades, aprobaste la materia.',
       'Felicidades, aprobaste la materia.',
       'Lo sentimos, no aprobaste la materia.',
       'Felicidades, aprobaste la materia.',
       'Lo sentimos, no aprobaste la materia.',
       'Felicidades, aprobaste la materia.'], dtype='<U37')

La funcion select sirve para hacer uso de mas de dos condiciones, para ello debemos seguir los siguiente pasos.

Primero creamos una lista de condicionales.

In [14]:
condiciones = [
    (calificaciones == 10),
    ( (calificaciones == 8) | (calificaciones == 9)),
    (calificaciones == 7),
    (calificaciones < 7)
]

Despues creamos una lista de mensajes para cada condicion.

In [15]:
mensajes = [
    'Felicidades, aprobaste la materia con 10',
    'Felicidades, aprobaste la materia',
    'Aprobaste la materia',
    'Lo sentimos, no aprobaste la materia'
]

Por ultimo hacemos uso de np.select().
Dentro de los () agregamos la lista de condiciones en el primer parametro
y la lista de mensajes en la segunda opcion.
El resultado es igual al de where, un arreglo con los mensajes de la lista mensajes,
los mensajes estaran en el lugar del arreglo que correcpondan a los elementos del arreglo original
que cumplan tal o cual condicion.

In [16]:
np.select(condiciones, mensajes)

array(['Felicidades, aprobaste la materia',
       'Lo sentimos, no aprobaste la materia',
       'Felicidades, aprobaste la materia',
       'Lo sentimos, no aprobaste la materia',
       'Felicidades, aprobaste la materia',
       'Felicidades, aprobaste la materia',
       'Lo sentimos, no aprobaste la materia',
       'Felicidades, aprobaste la materia',
       'Lo sentimos, no aprobaste la materia', 'Aprobaste la materia'],
      dtype='<U40')

NOTA: En el caso de where y select, si se modifica el arreglo original de donde esas dos funciones toman elementos,
debemos volver a crear o correr los pasos para cada duncion, ya qie de lo contrario, los resultados obtenidos
seran iguales a como se encontraba el arreglo originalmente y no con la actualizacion o cambio.
Ademas, esto no es como las condicionales if y else, asi que antes de trabajar con estas funciones,
debes evaluar todas las posibles condiciones o casos que se podrian dar en tu arreglo
y trabajar sobre esos casos o condiciones.

In [18]:
a = np.random.randint(0,10,10)
a

array([9, 0, 3, 2, 6, 9, 4, 0, 9, 2])

### Crear y leer archivos con Numpy

La funcion savetxt nos permite guardar un arreglo en un archivo de texto. Los argumentos dentro de los () indican el nombre del archivo y el arreglo a guardar en el archivo.

In [19]:
np.savetxt('archivo.txt', a)

Con la funcion %loadtxt podemos leer un archivo de texto. 

In [20]:
# %load archivo.txt
9.000000000000000000e+00
9.000000000000000000e+00
1.000000000000000000e+00
7.000000000000000000e+00
5.000000000000000000e+00
9.000000000000000000e+00
9.000000000000000000e+00
0.000000000000000000e+00
4.000000000000000000e+00
6.000000000000000000e+00


6.0

EL resultado de %loadtxt son los datos almacenados en formato conmplex. Para que los datos de guarden en el formato que queremos, debemos especificarlo con el parametro fmt. En este caso, '%i' indica que los datos se guardaran como enteros. Existen otros formatos, como '%f' para float, '%s' para string, etc.

In [21]:
np.savetxt('archivo.txt', a, fmt='%i')


In [22]:
# %load archivo.txt
9
9
1
7
5
9
9
0
4
6


6

Con la funcion loadtxt podemos leer un archivo de texto, el resultado, que es el contenido del archivo que se lee, sera guardado en un nuevo arreglo, que son objetos de tipo float por default.

In [23]:
np.loadtxt('archivo.txt')

array([9., 0., 3., 2., 6., 9., 4., 0., 9., 2.])

Podemos usar el parametro dtype para especificar el tipo de dato que queremos que tenga el nuevo arreglo.

In [24]:
np.loadtxt('archivo.txt', dtype=int)

array([9, 0, 3, 2, 6, 9, 4, 0, 9, 2])

Con la funcion reshape podemos cambiar la forma de un arreglo, siempre y cuando el nuevo tamaño sea compatible con el tamaño original del arreglo. En este caso, estamos cambiando un arreglo de 10 elementos a una matriz de 2 filas y 5 columna.

In [8]:
b = np.random.randint(0,10,10)

c = b.reshape((2,5))

c

array([[0, 0, 1, 6, 8],
       [2, 2, 4, 8, 3]])

Podemos crear archivos CSV utilizando la funcion savetxt. Los parametros dentro de los () indican el nombre del archivo que se va a crear, el arreglo que se guardara en el archivo, el delimitador entre cada elemento (en este caso una coma) y el formato de los datos (en este caso enteros).

In [9]:
np.savetxt('matriz.csv', c, delimiter=',', fmt='%i')

In [10]:
# %load matriz.csv
4
1
5
8
0
2
3
6
4
5


5

De igual manera, podemos leer archivos CSV utilizando la funcion loadtxt. Los elementos dentro del archivo se guardaran en un nuevo arreglo.

In [6]:
d = np.loadtxt('matriz.csv', delimiter=',', dtype=int)
d

array([[5, 4, 5, 6, 5],
       [9, 7, 9, 9, 5]])

Otra manera de crear y leer archivos es mediante las funciones save y load.
La diferencia entre esta y la manera anterior es que en este procedimiento los datos se guardaran en binario, mientras que en la manera anterios los datos se guardan en texto plano.

En este caso, en el nombre del archivo a crear, el formato del archivo es npy, que indica que el archivo es un archivo numpy.
Cabe recalcar que

In [2]:
y = np.random.randint(0,10,10)

np.save('arreglo_binario.npy', y)

np.load('arreglo_binario.npy')

array([2, 6, 6, 6, 4, 8, 6, 0, 2, 4])

### Modficar arreglos

Primero debemos recordar que los arreglos son inmutables, no se puede modificar su tamaño, pero si se pueden modificar sus elementos. 
Tambien se puede agregar o eliminar elementos, pero eso no quiere decir que se modifico el arreglo original, lo que pasa es que se crea un nuevo arreglo basandose en el arreglo original, pero con los cambios que se le hayan hecho.

Como podemos ver en los siqguientes ejemplos, podemos agregar elementos con las funciones insert y append. 
La diferencia es que con insert podemos agregar un elemento en cualquier posición que querramos de nuestro arreglo indicando en los parametros el arreglo a modificar seguido de la posición en la que se agregara y el valor a agregar, mientras que con append cualquier elemento que agreguemos se añadira al final del arreglo.

In [ ]:
z = np.random.randint(0,10,10)

np.insert(z, 0, 100)

array([100,   0,   6,   9,   2,   8,   7,   3,   4,   8,   1])

In [ ]:
np.append(z, 100)

array([  0,   6,   9,   2,   8,   7,   3,   4,   8,   1, 100])

La funcion delete nos permite eliminar cualquier elemento que se encuentre en cualquier posicón de nuestro arreglo.
Basta con indicar el arreglo a modificar y la posición en la que se enecuentra el elemento a eliminar.

In [ ]:
np.delete(z, 0)

array([6, 9, 2, 8, 7, 3, 4, 8, 1])

Con la funcion resize podemos cambiar el tamaño de un arreglo. 
Basta con indicar el arreglo a modificar y el nuevo tamaño que queremos que tenga el arreglo.
En este caso, el arreglo original tenia 10 elementos y con resize lo cambiamos a 5 elementos.
Los elementos que se quedan en el arreglo son los 5 primeros o los primeros que sean dependiendo el numero que se indique en el segundo parametro.

In [ ]:
np.resize(z, 5)

array([0, 6, 9, 2, 8])

Con la función concatenar podemos unir dos o más arreglos en uno nuevo arreglo.
Cabe recalcar que los datos se guardaran en el mismo orden en el que se indican los arreglos en los parametros, en este caso,
primero se añaden los elementos del arreglo r y despues los del arreglo k.

In [ ]:
r = np.array([50, 60, 100, 88, 45])
k = np.array([400, 550, 870, 1000])

np.concatenate([r, k])

array([  50,   60,  100,   88,   45,  400,  550,  870, 1000])

### Ordenamiento de arreglos

Con la fucnción sort podemos aordenar los elementos de menor a mayor. Como podemos ver, en el primer bloque de codigo, el arreglo creado contiene elementos desordenados, pero al aplicar sort(), los elemetos se ordenan de menor a mayor. Esto si modifica el arreglo original. 

In [ ]:
p = np.random.randint(0,20,30)
p

array([12,  9, 12,  8,  9,  7,  2,  1,  0,  4,  6, 14, 19,  7, 11,  7, 12,
       17,  9,  6,  2, 13, 17,  6, 11, 15,  7,  4,  2, 11])

In [ ]:
p.sort()
p

array([ 0,  1,  2,  2,  2,  4,  4,  6,  6,  6,  7,  7,  7,  7,  8,  9,  9,
        9, 11, 11, 11, 12, 12, 12, 13, 14, 15, 17, 17, 19])

Si aplicamos el slicing [::-1] el arreglo se ordenara de mayor a menor, pero esto solo es una vista del arreglo, no lo modifica. Si queremos que el arreglo original se modifique, debemos asignar el resultado del slicing a la variable del arreglo, en este caso p = p[::-1].

Cabe recalcar que primero debemos ordenar el arreglo de manera ascendente con sort() y despues ya podemos aplicar cualquiera de las dos funciones para ordenar de manera descendente.

In [ ]:
p[::-1]

array([19, 17, 17, 15, 14, 13, 12, 12, 12, 11, 11, 11,  9,  9,  9,  8,  7,
        7,  7,  7,  6,  6,  6,  4,  4,  2,  2,  2,  1,  0])

In [ ]:
p


array([ 0,  1,  2,  2,  2,  4,  4,  6,  6,  6,  7,  7,  7,  7,  8,  9,  9,
        9, 11, 11, 11, 12, 12, 12, 13, 14, 15, 17, 17, 19])

In [ ]:
p = p[::-1]
p

array([19, 17, 17, 15, 14, 13, 12, 12, 12, 11, 11, 11,  9,  9,  9,  8,  7,
        7,  7,  7,  6,  6,  6,  4,  4,  2,  2,  2,  1,  0])

Si lo que queremos es crear un nuevo arreglo ordenado sin modificar el original, podemos utilizar np.sort().
Indicando dentro de () el arreglo a ordenar. 

In [ ]:
np.sort(p)

array([ 0,  1,  2,  2,  2,  4,  4,  6,  6,  6,  7,  7,  7,  7,  8,  9,  9,
        9, 11, 11, 11, 12, 12, 12, 13, 14, 15, 17, 17, 19])

Si queremos crear un nuevo arreglo ordenado de manera descendente, podemos combinar np.sort() con el slicing [::-1].

In [ ]:
p = np.sort(p)[::-1]
p

array([19, 17, 17, 15, 14, 13, 12, 12, 12, 11, 11, 11,  9,  9,  9,  8,  7,
        7,  7,  7,  6,  6,  6,  4,  4,  2,  2,  2,  1,  0])